defmodule AssetMonitoringDash.EventStore do
  @moduledoc """
  Persistent store for generated demo events.

  Seeded events still come from `EventFeed`; this store only keeps actions
  generated by scenario controls and operator workflow.
  """

  import Ecto.Query

  alias AssetMonitoringDash.ActivityEventRecord
  alias AssetMonitoringDash.Assets
  alias AssetMonitoringDash.EventFeed
  alias AssetMonitoringDash.Repo
  alias AssetMonitoringDash.ReviewAudit

  def visible_events do
    persisted_events()
    |> EventFeed.visible_events()
  end

  def visible_events_for_asset(asset_id) do
    asset_id = Assets.normalize_asset_id(asset_id)

    persisted_events()
    |> EventFeed.visible_events_for_asset(asset_id)
  end

  def push_price_shock_event(asset, drop_percent) do
    event =
      []
      |> EventFeed.push_price_shock_event(asset, drop_percent)
      |> Map.fetch!(:visible_events)
      |> List.first()

    persist_event!(event)

    visible_events()
  end

  def push_scenario_reset_event(asset) do
    event =
      []
      |> EventFeed.push_scenario_reset_event(asset)
      |> Map.fetch!(:visible_events)
      |> List.first()

    persist_event!(event)

    visible_events()
  end

  def push_review_event(asset, review_state, audit_context \\ %{}) do
    event =
      []
      |> EventFeed.push_review_event(asset, review_state, audit_context)
      |> Map.fetch!(:visible_events)
      |> List.first()

    persist_event!(event)

    visible_events()
  end

  def reset_all do
    Repo.delete_all(ActivityEventRecord)

    :ok
  end

  defp persisted_events do
    ActivityEventRecord
    |> order_by([event], desc: event.occurred_at, desc: event.id)
    |> Repo.all()
    |> Enum.map(&record_to_event/1)
  end

  defp persist_event!(event) do
    %ActivityEventRecord{}
    |> ActivityEventRecord.changeset(event_attrs(event))
    |> Repo.insert!(
      on_conflict:
        {:replace_all_except,
         [
           :id,
           :inserted_at
         ]},
      conflict_target: :event_key
    )
  end

  defp event_attrs(event) do
    review_audit = ReviewAudit.normalize(Map.get(event, :review_audit, %{}))

    %{
      asset_id: event_asset_id(event),
      chain: event.chain,
      detail: event.detail,
      event_key: event.id,
      kind: event.kind |> Atom.to_string(),
      operator_note: review_audit.note,
      occurred_at: DateTime.truncate(event.occurred_at || DateTime.utc_now(), :microsecond),
      review_reason: review_audit.reason,
      status: event.status,
      title: event.title,
      tone: event.tone |> Atom.to_string()
    }
  end

  defp event_asset_id(%{asset_id: nil}), do: nil
  defp event_asset_id(%{asset_id: asset_id}), do: Assets.resolve_persisted_asset_id(asset_id)
  defp event_asset_id(_event), do: nil

  defp record_to_event(record) do
    %{
      id: record.event_key,
      asset_id: record.asset_id,
      actor: actor(record.kind),
      chain: record.chain,
      detail: record.detail,
      kind: kind_atom(record.kind),
      occurred_at: record.occurred_at,
      operator_note: record.operator_note,
      review_audit: ReviewAudit.new(%{note: record.operator_note, reason: record.review_reason}),
      review_reason: record.review_reason,
      source_label: source_label(record.kind),
      source_tone: source_tone(record.kind),
      source_value: record.kind,
      status: record.status,
      severity_label: severity_label(record.tone),
      severity_tone: severity_tone(record.tone),
      time_label: "now",
      title: record.title,
      tone: tone_atom(record.tone)
    }
  end

  defp kind_atom("operator"), do: :operator
  defp kind_atom("scenario"), do: :scenario
  defp kind_atom(_kind), do: :system

  defp tone_atom("danger"), do: :danger
  defp tone_atom("success"), do: :success
  defp tone_atom("warning"), do: :warning
  defp tone_atom(_tone), do: :neutral

  defp source_label("operator"), do: "Operator"
  defp source_label("scenario"), do: "Scenario"
  defp source_label(_kind), do: "System"

  defp source_tone("operator"), do: :success
  defp source_tone("scenario"), do: :warning
  defp source_tone(_kind), do: :info

  defp severity_label("danger"), do: "Critical"
  defp severity_label("success"), do: "Normal"
  defp severity_label("warning"), do: "Watch"
  defp severity_label(_tone), do: "Info"

  defp severity_tone("danger"), do: :danger
  defp severity_tone("success"), do: :success
  defp severity_tone("warning"), do: :warning
  defp severity_tone(_tone), do: :neutral

  defp actor("operator"), do: "Operator"
  defp actor("scenario"), do: "Scenario engine"
  defp actor(_kind), do: "Monitoring system"
end
