defmodule AssetMonitoringDash.EventStore do
  @moduledoc """
  Runtime store for generated demo events.

  Seeded events still come from `EventFeed`; this store only keeps actions
  generated by scenario controls and operator workflow.
  """

  use Agent

  alias AssetMonitoringDash.EventFeed

  def start_link(opts) do
    Agent.start_link(fn -> [] end, Keyword.put_new(opts, :name, __MODULE__))
  end

  def visible_events do
    ensure_started()

    Agent.get(__MODULE__, &EventFeed.visible_events/1)
  end

  def visible_events_for_asset(asset_id) do
    ensure_started()

    Agent.get(__MODULE__, &EventFeed.visible_events_for_asset(&1, asset_id))
  end

  def push_price_shock_event(asset, drop_percent) do
    ensure_started()

    update_events(&EventFeed.push_price_shock_event(&1, asset, drop_percent))
  end

  def push_scenario_reset_event(asset) do
    ensure_started()

    update_events(&EventFeed.push_scenario_reset_event(&1, asset))
  end

  def push_review_event(asset, review_state, audit_context \\ %{}) do
    ensure_started()

    update_events(&EventFeed.push_review_event(&1, asset, review_state, audit_context))
  end

  def reset_all do
    ensure_started()

    Agent.update(__MODULE__, fn _events -> [] end)
  end

  defp ensure_started do
    case Process.whereis(__MODULE__) do
      nil -> start_standalone()
      _pid -> :ok
    end
  end

  defp start_standalone do
    case start_link([]) do
      {:ok, _pid} -> :ok
      {:error, {:already_started, _pid}} -> :ok
    end
  end

  defp update_events(fun) do
    Agent.get_and_update(__MODULE__, fn events ->
      events = fun.(events).visible_events

      {EventFeed.visible_events(events), events}
    end)
  end
end
